---
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Title

Casey Perkins, Bryn Rivenes

Dr. Chris Merkord

## Introduction

Ecogeographic rules explain variation within a species using biogeography. Allen's rule states that body surface-area-to-volume ratio for animals varies with the average temperature of their habitat. Typically, latitude is used as the temperature variable. However, this rule should hold true over any type of temperature variable. We want to know, is there a correlation between altitude and ratio of mass to length of birds in The Atlantic Forest? To answer this question, we will be using the Atlantic Bird Traits data set. This data set has been compiled over two centuries by tens of researchers (1820-2018) and includes data on 80% of the bird populations found in The Atlantic Forest. We will perform an exploratory analysis on this data set looking for correlations between altitude and ratio of mass to length of bird species. Based on other similar analyses, we expect to see a positive correlation between these variables.

## Methods

## Results

## Discussion

We began with the question, "does altitude correlate with the mass to length ratio?" We began with a simple frequency plot for our data. We found our data had a serious right skew. To correct for this, we took the natural log of all of our data points and re-plotted the data. We found the data had two peaks. To explore what might be causing this bimodal distribution, we separated the data out into frequency plots by order. This showed us the source of the smaller lump in our data was coming from a order of birds called Anseriformes (ducks). The larger lump in the data was caused by the order Passerifomes (songbirds). This makes sense because Passeriformes make up the majority of the known birds in the world.

## References

-   Blackburn T, Ruggiero A. Latitude, elevation and body mass variation in Andean passerine birds. Global Ecology and Biography 2001 (cited 2022 Feb 18); 10: 245-259.

-   Lamichhaney S, Han F, Berglund J, Wang C, Almén MS, Webster MT, Grant BR, Grant PR, Andersson L. A beak size locus in Darwin's finches facilitated character displacement during a drought. Science. 2016 (cited 2022 Feb 18);352(6284):470-4

-   Landmann A, Winding N. Guild Organization and Morphology of High-Altitude Granivorous and Insectivorous Birds: Convergent Evolution in an Extreme Environment. Oikos. 2995 (cited 2022 Feb 18);73(2):237-250.

-   Sun Y, Li M, Song G, Lei F, Li D, Wu Y. The Role of Climate Factors in Geographic Variation in Body Mass and Wing Length in a Passerine Bird. Avian Res. 2017 (cited 2022 Feb 19); 8, 1.

## Acknowledgments
